variable "ami" {}
variable "nexus_sg" {}
variable "subnet_id" {}
variable "keypair" {}
variable "name" {}
variable "elb-subnet" {}
variable "cert-arn" {}
variable "nr-key" {}
variable "nr-acc-id" {}
variable "nr-region" {}
