variable "ami" {}
variable "subnet_id" {}
variable "key_name" {}
variable "jenkins_sg" {}
variable "name" {}
variable "elb-subnets" {}
variable "cert-arn" {}
variable "nexus-ip" {}
variable "nr-key" {}
variable "nr-acc-id" {}
variable "nr-region" {}