variable "sonarqube_elb_zone_id" {}
variable "sonarqube_elb_dns_name" {}
variable "domain_name" {}
variable "nexus_elb_dns_name" {}
variable "nexus_elb_zone_id" {}
variable "nexus_domain_name" {}
variable "sonarqube_domain_name" {}
variable "jenkins_domain_name" {}
variable "jenkins_elb_dns_name" {}
variable "jenkins_elb_zone_id" {}
variable "stage_domain_name" {}
variable "stage_lb_dns_name" {}
variable "stage_lb_zone_id" {}
variable "prod_domain_name" {}
variable "prod_lb_dns_name" {}
variable "prod_lb_zone_id" {}
